-- ─────────────────────────────────────────
-- CREATE TABLES
-- ─────────────────────────────────────────

-- ─────────────────────────────────────────
-- 1. CUSTOMERS
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
	customer_id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	customer_name VARCHAR(255) NOT NULL,
	customer_email VARCHAR(255) NOT NULL UNIQUE,
	customer_address VARCHAR(255) NOT NULL,
	customer_phone  VARCHAR(20) NOT NULL,
	PRIMARY KEY(customer_id)
);

-- ─────────────────────────────────────────
-- 2. SUPPLIERS
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "suppliers" (
	"supplier_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"supplier_name" VARCHAR(255) NOT NULL UNIQUE,
	"supplier_email" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("supplier_id")
);

-- ─────────────────────────────────────────
-- 3. CATEGORIES
-- ─────────────────────────────────────────

-- ─────────────────────────────────────────
-- 4. PRODUCTS
-- ─────────────────────────────────────────

-- ─────────────────────────────────────────
-- 5. TRANSACTIONS
-- ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "transactions" (
	"transaction_id" VARCHAR(100) NOT NULL UNIQUE,
	"date" DATE NOT NULL,
	"customer_id" INTEGER NOT NULL,
	"product_sku" VARCHAR(255) NOT NULL,
	"supplier_id" INTEGER NOT NULL,
	PRIMARY KEY("transaction_id")
);



CREATE TABLE IF NOT EXISTS "products" (
	"product_sku" VARCHAR(100) NOT NULL UNIQUE,
	"product_name" VARCHAR(255) NOT NULL,
	"unit_price" NUMERIC NOT NULL,
	"quantity" INTEGER NOT NULL,
	"total_line_value" INTEGER NOT NULL,
	"category_id" INTEGER NOT NULL,
	PRIMARY KEY("product_sku")
);




CREATE TABLE IF NOT EXISTS "categories" (
	"category_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"category" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("category_id")
);








ALTER TABLE "suppliers"
ADD FOREIGN KEY("supplier_id") REFERENCES "transactions"("supplier_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactions"
ADD FOREIGN KEY("product_sku") REFERENCES "products"("product_sku")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactions"
ADD FOREIGN KEY("customer_id") REFERENCES "customers"("customer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "products"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("category_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;